sonar.projectKey=artiplast-inventory
sonar.projectName=ARTIPLAST Inventory
sonar.projectVersion=1.0

sonar.sources=app,routes,resources/views,database,config
sonar.exclusions=vendor/**,node_modules/**,storage/**,public/build/**,tests/**,bootstrap/cache/**,public/backend/**,public/upload/**

sonar.sourceEncoding=UTF-8
sonar.language=php
